name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start HTTP Server
      run: npx http-server . -p 8080 & # Start server in background
    - name: Run Playwright E2E tests
      run: npm run test:e2e
    - name: Stop HTTP Server # This step might not be strictly necessary as the job will terminate, but good practice
      if: always()
      run: kill $(jobs -p)
